name: "🔃 Pull Request"
description: "PR 요청"
labels: ["pull-request"]
body:
  - type: input
    attributes:
      label: 📎 Issue
      description: Issue Number
      placeholder: "#Issue Number"
    validations:
      required: true
  - type: textarea
    attributes:
      label: 💫 작업 내용
      description: 작업한 내용을 설명해주세요.
      placeholder: |
        - 구현 내용 요약
        - 변경사항 설명
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: ✅ 체크리스트
      options:
        - label: 변경 사항에 대한 테스트를 진행했습니다.
        - label: 불필요한 코드가 없습니다.
