services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kefa_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kefa
      SPRING_DATASOURCE_USERNAME: bongsan
      SPRING_DATASOURCE_PASSWORD: 1111
      SPRING_REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: kefa_postgres
    restart: always
    environment:
      POSTGRES_USER: bongsan
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: kefa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: kefa_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: kefa_jenkins
    restart: always
    ports:
      - "8282:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # 도커 사용을 위한 볼륨
    environment:
      - TZ=Asia/Seoul  # 타임존 설정

volumes:
  postgres_data:
  redis_data:
  jenkins_home:
