services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kefa_app
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:16.2
    container_name: kefa_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7.2.4
    container_name: kefa_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: kefa_jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - "${JENKINS_PORT}:8080"
      - "${JENKINS_AGENT_PORT}:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      - JAVA_OPTS="-Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.PROXY_COMPATIBILITY=true"
    depends_on:
      - db
      - redis
    networks:
      - app-network

  smee-client:
    image: deltaprojects/smee-client
    container_name: kefa_smee
    command: >
      -u ${SMEE_URL}
      -t ${SMEE_TARGET}
    depends_on:
      - jenkins
    restart: always
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  jenkins_home:

networks:
  app-network:
    driver: bridge
