services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kefa_app
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:16.2
    container_name: kefa_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7.2.4
    container_name: kefa_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: kefa_jenkins
    restart: always
    privileged: true
    user: root
    ports:
      - "${JENKINS_PORT}:8080"
      - "${JENKINS_AGENT_PORT}:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/var/jenkins_home/.ssh
    environment:
      - TZ=${TZ}
      - JAVA_OPTS="-Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.PROXY_COMPATIBILITY=true"
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - app-network
    command: |
      bash -c '
        DOCKER_GID=$(stat -c '%g' /var/run/docker.sock)
        groupadd -g ${DOCKER_GID} docker || true
        usermod -aG docker jenkins
        mkdir -p /var/jenkins_home/jobs
        mkdir -p /var/jenkins_home/workspace
        chown -R jenkins:jenkins /var/jenkins_home
        chmod -R 777 /var/jenkins_home
        /usr/local/bin/jenkins.sh
      '

  smee-client:
    image: deltaprojects/smee-client
    container_name: kefa_smee
    command: >
      -u ${SMEE_URL}
      -t ${SMEE_TARGET}
    depends_on:
      - jenkins
    restart: always
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  jenkins_home:

networks:
  app-network:
    driver: bridge
