spring:
  application:
    name: kefa

  datasource:
    url: jdbc:postgresql://localhost:5432/kefa
    username: bongsan
    password: 1111
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
