spring:
  application:
    name: kefa

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:

jwt:
  key: ${JWT_KEY}
  access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME}
  refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}